name: Documentation

on:
  push:
    branches: [documentation]
  pull_request:
    branches: [documentation]

jobs:
  deploy:
    uses: ConductionNL/.github/.github/workflows/documentation.yml@main
    with:
      cname: versioniq.conduction.nl

      docs-hosts: app-versions.conduction.nl,versioniq.conduction.nl